Added support for multiple channels and managing channels from admin
Setono/SyliusCriteoPlugin pull request #4
Opened 2019-03-18 13:36 UTC by Peteck

2019-03-18 13:46 UTC, loevgaard requested changes

2019-03-18 13:46 UTC, loevgaard commented on src/Resources/config/services/menu.xml
> +        <service id="setono_sylius_criteo_plugin.listener.menu.account_config" class="Setono\SyliusCriteoPlugin\Menu\AdminMenuListener">
```suggestion
        <service id="Setono\SyliusCriteoPlugin\Menu\AdminMenuListener">
```

2019-03-18 13:46 UTC, loevgaard commented on src/Resources/config/validation/CriteoConfig.yaml
> +Setono\SyliusCriteoPlugin\Model\CriteoConfig:
Lav validering i XML

2019-03-18 13:46 UTC, loevgaard commented on tests/Application/.env
> +DATABASE_URL=mysql://root:pass@localhost/sylius_criteo_plugin_test?serverVersion=5.5
```suggestion
DATABASE_URL=mysql://root:pass@localhost/setono_sylius_criteo_%kernel.environment%?serverVersion=5.5
```

2019-03-18 13:46 UTC, loevgaard commented on tests/Application/config/services.yaml
> +    - { resource: "@SetonoSyliusCriteoPlugin/Resources/config/app/config.yaml" }
Skal imporeteres i `packages/_sylius.yaml`

2019-03-18 13:46 UTC, loevgaard commented on src/EventListener/ViewListSubscriber.php
> +    public function __construct(TagBagInterface $tagBag, AccountContextInterface $account, ProductIdResolverInterface $productIdResolver)
```suggestion
    public function __construct(TagBagInterface $tagBag, AccountContextInterface $accountContext, ProductIdResolverInterface $productIdResolver)
```

2019-03-18 13:46 UTC, loevgaard commented on src/EventListener/ViewBasketSubscriber.php
> +    public function __construct(TagBagInterface $tagBag, AccountContextInterface $account, string $route, CartContextInterface $cartContext)
```suggestion
    public function __construct(TagBagInterface $tagBag, AccountContextInterface $accountContext, string $route, CartContextInterface $cartContext)
```

2019-03-18 13:46 UTC, loevgaard commented on src/EventListener/RouteTagSubscriber.php
> +    public function __construct(TagBagInterface $tagBag, AccountContextInterface $account, string $route)
```suggestion
    public function __construct(TagBagInterface $tagBag, AccountContextInterface $accountContext, string $route)
```

2019-03-18 13:46 UTC, loevgaard commented on src/EventListener/AddLibrarySubscriber.php
> +    public function __construct(TagBagInterface $tagBag, AccountContextInterface $account, SiteTypeResolver $siteTypeResolver)
```suggestion
    public function __construct(TagBagInterface $tagBag, AccountContextInterface $accountContext, SiteTypeResolver $siteTypeResolver)
```

2019-03-18 13:46 UTC, loevgaard commented on src/Resources/config/doctrine/model/Account.orm.xml
> +        <field name="accountId" type="string" />
```suggestion
        <field name="accountId" type="string" unique=true />
```

2019-03-18 14:08 UTC, loevgaard requested changes

2019-03-18 14:08 UTC, loevgaard commented on src/Context/AccountContext.php
> +        } catch (ChannelNotFoundException $e) {
`ChannelNotFoundException` bliver vel kastet, hvis man ikke er på en channel, eller der ikke er oprettet nogle channels.

2019-03-18 14:25 UTC, Peteck commented on src/Context/AccountContext.php
> +        } catch (ChannelNotFoundException $e) {
Jeg oplevede nogen problemer med det da jeg udviklede det og lavede en ny channel, men oplever ikke det problem længere, så jeg fjerner det bare igen.

2019-03-19 07:49 UTC, loevgaard requested changes

2019-03-19 07:49 UTC, loevgaard commented on phpunit.xml.dist
> +            <directory>tests/phpunit</directory>
Ikke lav om i standard. PHPUnit filer ligger i `tests`

2019-03-19 07:49 UTC, loevgaard commented on src/Context/AccountContext.php
> +     * Returns the account enabled for the active channel
Dokumentation af metoder hører hjemme i interfacet

2019-03-19 07:49 UTC, loevgaard commented on src/EventListener/AddLibrarySubscriber.php
> +        if ($account === null) {
```suggestion
        if (null === $account) {
```

2019-03-19 07:49 UTC, loevgaard commented on src/EventListener/TrackTransactionSubscriber.php
> +        if ($this->accountContext->getAccount() === null) {
Det er god skik at lave guards i den rækkefølge der er hurtigst. I det her tilfælde, så er guarden med `instanceof` (som kommer nedenunder) hurtigere end denne

2019-03-19 07:49 UTC, loevgaard commented on src/EventListener/ViewListSubscriber.php
> +        if ($this->accountContext->getAccount() === null) {
Samme kommentar vedr. rækkefølge

2019-03-19 07:49 UTC, loevgaard commented on src/EventListener/ViewProductSubscriber.php
> +        if ($this->accountContext->getAccount() === null) {
Samme kommentar vedr. rækkefølge

2019-03-19 07:49 UTC, loevgaard commented on src/Form/Type/AccountType.php
> +            ->add('accountId', TextType::class, [
Bruger [IntegerType](https://symfony.com/doc/current/reference/forms/types/integer.html) i stedet og brug evt. HTML5-attributter til at sige, at den skal minimum være 1

2019-03-19 07:49 UTC, loevgaard commented on src/Menu/AdminMenuListener.php
> +            ->setLabel('setono_sylius_criteo.ui.menu_item')
Hvis man lavede et menu punkt mere, ville være have svært ved at vælge et navn til det. Derfor skal denne hedde `setono_sylius_criteo.ui.criteo`

2019-03-19 07:49 UTC, loevgaard commented on src/Menu/AdminMenuListener.php
> +            ->setLabelAttribute('icon', 'bullhorn');
Føl dig fri til at finde et bedre ikon: https://semantic-ui.com/elements/icon.html. Bullhorn bliver brugt til Analytics. Synes det kunne være fedt, hvis man fandt et ikon, der ikke blev brugt :D

2019-03-19 07:49 UTC, loevgaard commented on src/Repository/AccountRepositoryInterface.php
> +     * Returns the account that is enabled on the given channel
```suggestion
     * Returns the account that is enabled on the given channel or null if no account is enabled for the given channel
```

2019-03-19 07:49 UTC, loevgaard commented on src/Resources/config/doctrine/model/Account.orm.xml
> +    <entity name="Setono\SyliusCriteoPlugin\Model\Account" table="setono_sylius_criteo_account">
```suggestion
    <entity name="Setono\SyliusCriteoPlugin\Model\Account" table="setono_sylius_criteo__account">
```

2019-03-19 07:49 UTC, loevgaard commented on src/Resources/config/routing/admin.yaml
> +                icon: 'file image outline'
Det her ikon skal være det samme som det du bruger i menupunktet

2019-03-19 07:49 UTC, loevgaard commented on src/Resources/config/routing/admin.yaml
> +                subheader: setono_sylius_criteo.ui.account
Tror den her skal hedde
```suggestion
                subheader: setono_sylius_criteo.ui.manage_accounts
```

2019-03-19 07:49 UTC, loevgaard commented on src/Resources/config/doctrine/model/Account.orm.xml
> +        <one-to-one field="channel" target-entity="Sylius\Component\Channel\Model\ChannelInterface" />
Der mangler forresten nok en [join column](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-one-unidirectional) her, som der kan sættes `nullable=false` på

2019-03-19 07:49 UTC, loevgaard commented on src/Resources/translations/messages.en.yaml
> +        account_id_placeholder: Insert your acciynt id, i.e. 392871
```suggestion
        account_id_placeholder: Insert your account id, i.e. 392871
```

2019-03-19 07:49 UTC, loevgaard commented on tests/Behat/Page/Shop/HomePage.php
> +        if ($libResult === false) {
```suggestion
        if (false === $libResult) {
```

2019-03-19 09:35 UTC, loevgaard requested changes

2019-03-19 09:35 UTC, loevgaard commented on src/Resources/config/validation/account.xml
> +<constraint-mapping xmlns="http://symfony.com/schema/dic/constraint-mapping"
Filnavnet på denne skal være `Account.xml` (stort A)

2019-03-19 10:15 UTC, loevgaard commented
Husk også at opdatere README

2019-03-19 10:16 UTC, loevgaard requested changes

2019-03-19 10:16 UTC, loevgaard commented on README.md
> +Login to your Sylius app admin and go to the Criteo page and click "Create" to create a new account. Fill in the account id of your Criteo account, make sure "enable" is toggled on, and choose which
Mangler mere info i denne readme, f.eks. importering af routing og config

2019-03-22 13:41 UTC, loevgaard requested changes

2019-03-22 13:41 UTC, loevgaard commented on src/EventListener/AddLibrarySubscriber.php
> +        if (null === $account) {
Dette bliver brugt flere steder. Skal lægges i den abstrakte klasse. Se evt. https://github.com/Setono/SyliusAnalyticsPlugin/blob/master/src/EventListener/TagSubscriber.php#L35-L51

2019-03-22 13:41 UTC, loevgaard commented on src/Form/Type/AccountType.php
> +                'multiple' => false,
Fjern 'multiple' og 'expanded' og tilføj 'placeholder' med en tekst, der hedder 'Select channel...'

2019-03-22 14:34 UTC, loevgaard requested changes

2019-03-22 14:34 UTC, loevgaard commented on src/EventListener/ViewHomeSubscriber.php
> +        if ($this->accountContext->getAccount() === null) {
Brug metode i parent class

2019-03-25 06:58 UTC, loevgaard requested changes

2019-03-25 06:58 UTC, loevgaard commented on src/Resources/translations/validators.en.yaml
> +setono_sylius_criteo:
Der mangler tekster her jf. de constraints der er i `src/Resources/config/validation/Account.xml`

2019-03-25 08:08 UTC, loevgaard approved these changes

2019-03-25 08:35 UTC, merged